### PR TITLE
Fix preparation of $elemMatch operators in queries

### LINKED ISSUE #2251: $elemMatch not working like standard MongoDB one
Hi,

I'm trying to implement a MongoDB find query using an `$elemMatch`.

The query i want to recreate the following query:

```
{
   $nor:[
      {
         "children":{
            $elemMatch:{
               $nin:[
                  ObjectId("5fae9a775ef4492e3c72b3f3"),
                  ObjectId("5fae9a775ef4492e3c72b3f4")
               ]
            }
         }
      }
   ]
}
```

Right now i have the following query using a queryBuilder:

```
$query = $this->dm->createQueryBuilder(Target::class);

$query->addNor(
    $query->field('children')->elemMatch(
        $query->expr()->notIn([new ObjectId('5fae9a775ef4492e3c72b3f3'), new ObjectId('5fae9a775ef4492e3c72b3f4')])
    )
);
```

But when i try to run it, i'm getting the following error:

`ErrorException: Notice: Array to string conversion[0] (caught throwable) at /var/www/app/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Types/IdType.php line 22.`

I cant manage to find any solution or work around.

### PR DESCRIPTION
**Pull request by alcaeus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | Fixes #2251

#### Summary

Contrary to the suggestion in https://github.com/doctrine/mongodb-odm/issues/2251#issuecomment-734850221, the solution is to give `$elemMatch` the same treatment as `$not` and recurse the query preparation.

### CODE REVIEW

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2251Test.php [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;
+
+use Doctrine\ODM\MongoDB\Tests\BaseTest;
+use Documents\User;
+use MongoDB\BSON\ObjectId;
+
+class GH2251Test extends BaseTest
+{
+    /**
+     * @testWith ["groups"]
```
Comment (malarzm) [inline tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2251Test.php:14]: What's this?

**Review by malarzm — APPROVED** [review]
Ah the infamous `DocumentPersister:prepareQueryExpression` 🙈 Couldn't think of anything that might go south with this so 👍

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2251Test.php (hunk 1 above)
Comment (alcaeus) [reply tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2251Test.php:14]: This is a variant of data providers that doesn't require an extra method. It's useful when passing scalar values and reduces the test overhead.
