### PR TITLE
Fix discriminatorValue key 0

### LINKED ISSUE #2712: problem discriminatorValue with 0
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0

#### Summary

Problem when having a "discriminatorValue" with value 0

#### Current behavior

When the query is being composed, it checks this condition in DocumentPersister.php:1473 

```
  if (! $key) {
      continue;
  }
```

However, this means that having a discriminatorValue with a value of 0 is not allowed. Shouldn't it be something like $key !== false instead?

#### How to reproduce

Perform any document search when child classes have a discriminator with a value of 0.
    
```
    const CONTENT_TYPE_NWS = 0;
    const CONTENT_TYPE_IMA = 1;
    const MAPPING = [
        self::CONTENT_TYPE_NWS => ContentNews::class,
        self::CONTENT_TYPE_IMA => ContentImage::class,
    ];

```

### PR DESCRIPTION
**Pull request by parada85**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | fix #2712

#### Summary

Fix discriminatorValue 0

### CODE REVIEW

**Review by GromNaN — APPROVED** [review]

File: lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DiscriminatorMap.php [hunk 1]
```diff
@@ -16,7 +16,7 @@
 #[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_PROPERTY)]
 final class DiscriminatorMap implements Annotation
 {
-    /** @var array<string, class-string> */
+    /** @var array<class-string> */
     public $value;
 
     /** @param array<string, class-string> $value */
```
Comment (GromNaN) [inline lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DiscriminatorMap.php]:
```suggestion
    /** @param array<class-string> $value */
```

**Comment by GromNaN** [comment]
Thank you @parada85
