### PR TITLE
Validate that targetDocument can be resolved

### LINKED ISSUE #2576: Mapping validation does not validate targetDocument
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | maybe
| Version     | 2.5.x

#### Summary

Validity of `EmbedOne/EmbedMany/ReferenceOne/ReferenceMany` with `targetDocument` is not confirmed.

#### Current behavior

Running `doctrine:mongodb:mapping:info` or just warming up the `ClassMetadata` does not detect references within `EmbedOne/EmbedMany/ReferenceOne/ReferenceMany` to `targetDocument`s that cannot be resolved.

#### How to reproduce

```php
/** @ODM\Document */
class InvalidTargetDocumentTestDocument
{
    /**
     * @ODM\Id
     *
     * @var string|null
     */
    public $id;

    /**
     * @ODM\ReferenceOne(targetDocument=Doctrine\ODM\MongoDB\Tests\Functional\SomeInvalidClass::class)
     *
     * @var object|null
     */
    public $reference;
}
```

#### Expected behavior

`ClassMetadata` generation should fail or `doctrine:mongodb:mapping:info` should display an error.

### PR DESCRIPTION
**Pull request by buffcode**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | maybe
| Fixed issues | #2576 

#### Summary

Show an error when validating the `ClassMetadata`, if a `targetDocument` can neither be resolved to an existing interface or class.

```bash
$ bin/console doctrine:mongodb:mapping:info
[FAIL] InvalidTargetDocumentTestDocument
Target document class 'Doctrine\ODM\MongoDB\Tests\Functional\SomeInvalidClass' used in field 'reference' of class 'Doctrine\ODM\MongoDB\Tests\Functional\InvalidTargetDocumentTestDocument' does not exist.
```

BC breaks could occur, if current metadata contains undetected errors.

### CODE REVIEW

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/TargetDocumentTest.php [hunk 1]
```diff
@@ -18,6 +19,15 @@ public function testMappedSuperClassAsTargetDocument(): void
         $this->dm->persist($test->reference);
         $this->dm->flush();
     }
+
+    public function testTargetDocumentIsResolvable(): void
+    {
+        self::expectExceptionMessage("Target document class 'Doctrine\ODM\MongoDB\Tests\Functional\SomeInvalidClass' used in field 'reference' of class 'Doctrine\ODM\MongoDB\Tests\Functional\InvalidTargetDocumentTestDocument' does not exist.");
```
Comment (alcaeus) [inline tests/Doctrine/ODM/MongoDB/Tests/Functional/TargetDocumentTest.php]: Pro tip: use `expectException` with exception factories to not be impacted by exception message changes:
```suggestion
        self::expectException(MappingException::invalidTargetDocument(SomeInvalidClass::class, InvalidTargetDocumentTestDocument::class, 'reference'));
```

Note that the code suggestion will most likely need a couple of `use` statements.

**Review by alcaeus — COMMENTED** [review]
Great find. I have a small suggestion for checking the exception.

Did you check if invalid class names in a `discriminatorMap` are handled correctly?

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/TargetDocumentTest.php (hunk 1 above)
Comment (buffcode) [reply tests/Doctrine/ODM/MongoDB/Tests/Functional/TargetDocumentTest.php]: Thanks, good suggestion!

**Comment by buffcode** [comment]
> Did you check if invalid class names in a `discriminatorMap` are handled correctly?

The map is only checked on class level and throws `MappingException::invalidClassInDiscriminatorMap`. Field references aren't checked currently, I will add that as well.

**Review by alcaeus — APPROVED** [review]

**Comment by alcaeus** [comment]
Thanks @buffcode!
