### PR TITLE
Fix serialisation of uninitialised PersistentCollection instances

### LINKED ISSUE #1864: PersistentCollection instance lost raw data during serialization/deserialization process.
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 1.2.5

#### Summary

By default instance keep raw data from the database. So if you not accesses items from this collection before serialization, they will be not created from this raw data. This will cause lost of all data about items in collection during serialization/deserialization process. 
I solved this problem for itself by redefining PersistentCollection class - I added call of 'initialize' method in '_sleep'.

#### How to reproduce

1. Create instance of PersistentCollection with raw data.
2. Serialize instance.
3. Unserialize instance.
4. At this point data will be lost.

### PR DESCRIPTION
**Pull request by alcaeus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | Fixes #1864, Replaces #1914

#### Summary

This ensures that any internal data from `PersistentCollection` instances are serialised to have a usable collection instance after serialisation. This affects the `mongoData` and `snapshot` properties along with `isDirty` and `hints`.

Ping @watari

### CODE REVIEW

File: lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php [hunk 1]
```diff
@@ -582,7 +582,7 @@ public function slice($offset, $length = null)
      */
     public function __sleep()
     {
-        return array('coll', 'initialized');
+        return array('coll', 'initialized', 'mongoData', 'snapshot', 'isDirty', 'hints');
```
Comment (malarzm) [inline lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php]: Please update PHPDoc of the method as it's wrong now

**Comment by malarzm** [comment]
I still think that using unserialised `PersistentCollection` is a can of worms but this is better than #1914 :)

File: lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php (hunk 1 above)
Comment (alcaeus) [reply lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php]: Fixed!

**Comment by watari** [comment]
Hi there. Sorry for delay. First of all - thank you for PR with fix :)
But still `PersistentCollection` is unusable after serialization since It does not have link to UoW and cannot perform hydration of raw data. I agree with @malarzm , that `PersistentCollection` should not be serialized since it will be broken after unserialization.

I propose just to forget about this issue until it do not brake anything :) 

About my PR - it was bad in general and I did not count  references. In such way I fixed it for my projects and it was worked for me.
I think that this issue will be really actual when implementation of results caching in lib will begin.

**Comment by malarzm** [comment]
@watari for the record, unserialised collection will have `UnitOfWork` if you call [`->setDocumentManager()`](https://github.com/doctrine/mongodb-odm/blob/9aae6d067ba6d8b16b922c78c72cfee6c54df4f0/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php#L95)
