### PR TITLE
Fix embedded documents on inherited referenced documents

### LINKED ISSUE #872: Embedded documents on inherited referenced documents are not loaded correctly
It seems that Doctrine does not load embedded documents correctly behind referenced documents that are part of inheritance tree. Failing test case coming in a minute.

This resembles somehow the issue #562

### PR DESCRIPTION
**Pull request by malarzm**
Fixes #872, closes #873  

/cc @vmattila

### CODE REVIEW

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH872/GH872Test.php [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+        
+        $address = $location->getAddress();
+        $this->assertNotNull($address);
+
+        $this->assertEquals('Some address', $address->getStreetName());
+    }
+}
+
+/** @ODM\Document */
+class Event
```
Comment (jmikola) [inline tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH872/GH872Test.php]: @malarzm: I assume this file is nested under a `GH872/` directory in order to be consistent with the namespace? And the namespace was added because these class names might conflict with others in the general `Functional\Ticket` namespace?

Comment (malarzm) [inline tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH872/GH872Test.php]: I've merged @vmattila commit into this PR and that's how he's written test and since there was additional namespace and no chance for classname conflict I've left that :)
