### PR TITLE
Fix inheritance of GridFS mapping properties

### LINKED ISSUE #1855: [2.0] Correctly apply GridFS file settings when inheriting metadata
When extending a class mapped as GridFS file, the document level mapping options are not correctly applied to the child class.

### PR DESCRIPTION
**Pull request by alcaeus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | Fixes #1855

### CODE REVIEW

File: lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php [hunk 1]
```diff
@@ -14,8 +14,8 @@
     /** @var string|null */
     public $db;
 
-    /** @var string */
-    public $bucketName = 'fs';
+    /** @var string|null */
+    public $bucketName;
```
Comment (malarzm) [inline lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php]: I'd expect to find default value here from a user's perspective. Are you changing this for the sake of XML driver and default value?

File: lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php [hunk 2]
```diff
@@ -194,7 +194,7 @@ class ClassMetadata implements BaseClassMetadata
      *
      * @var string|null
      */
-    public $bucketName;
+    public $bucketName = 'fs';
```
Comment (malarzm) [inline lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php]: This can now be typed to `string`

File: lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php (hunk 1 above)
Comment (alcaeus) [reply lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php]: Without this change, just annotating an extending class as file without specifying a bucket name (as is done in the test I added) would reset the bucket name in the extending class to “fs”.

Comment (malarzm) [reply lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php]: Good point 👍

**Comment by alcaeus** [comment]
@malarzm type hint is updated.

**Comment by malarzm** [comment]
🎉
