### PR TITLE
Fix skipped tests

### LINKED ISSUE #1791: [2.0] Fix skipped tests
As evidenced in the master build, there are a bunch of skipped tests: https://travis-ci.org/doctrine/mongodb-odm/jobs/376653436#L1607. Some of these relate to sharding support, others (e.g. SchemaManagerTest) needs to be refactored.

### PR DESCRIPTION
**Pull request by alcaeus**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | Fixes #1791

### CODE REVIEW

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php [hunk 1]
```diff
@@ -580,35 +580,6 @@ public function testPrimeReferencesInReferenceMany()
         $this->assertTrue($comment->author->isProxyInitialized());
     }
 
-    public function testPrimeReferencesInReferenceManyWithRepositoryMethodThrowsException()
```
Comment (alcaeus) [inline tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php]: This test was added since we were requiring eager cursors in order to prime references; this is no longer a requirement so I decided to drop the test.

File: tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php [hunk 2]
```diff
@@ -566,26 +553,17 @@ public function testVersionIncrementOnUpdateSuccess()
...
-        $reflectionProperty->setValue($documentPersister, $collection);
+        $this->dm->getDocumentCollection($class)->updateOne([], ['$inc' => ['revision' => 1]]);
 
-        $testDocument     = new $class();
-        $testDocument->id = 12345;
-        $this->uow->registerManaged($testDocument, 12345, ['id' => 12345]);
-        $this->expectException(LockException::class);
         $testDocument->name = 'test';
         $this->dm->persist($testDocument);
+        $this->expectException(LockException::class);
```
Comment (malarzm) [inline tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php]: I think this was broken before, but `$this->assertEquals(1, $testDocument->revision);` won't be executed with exception thrown from `flush()`?

Comment (alcaeus) [reply tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php]: Yep. I'll drop it.
